Repository uPortal-Project/uPortal, pull requests merged in 2018-12, with the labels that each got.

#1441 Issue #1438: Support session-less access to uPortal REST APIs based …
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/GroupRESTController.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/swagger/SwaggerConfiguration.java
  uPortal-api/uPortal-api-rest/src/test/java/org/apereo/portal/rest/GroupRESTControllerTest.java
  uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/DistributedLayoutManager.java
  uPortal-security/uPortal-security-authn/src/main/java/org/apereo/portal/security/provider/RemoteUserPersonManager.java
  uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/oauth/IdTokenFactory.java
  uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/provider/BasePersonManager.java
  uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/services/PersonService.java
  uPortal-security/uPortal-security-mvc/src/main/java/org/apereo/portal/url/RequireValidSessionFilter.java
  uPortal-spring/src/main/java/org/apereo/portal/spring/security/evaluator/PortalPermissionEvaluator.java
  uPortal-spring/src/main/java/org/apereo/portal/spring/security/preauth/PortalPreAuthenticatedProcessingFilter.java
  uPortal-spring/src/test/java/org/apereo/portal/spring/security/preauth/PortalPreAuthenticatedProcessingFilterTest.java
  uPortal-spring/src/test/java/org/apereo/portal/spring/security/preauth/PortalPreAuthenticatedProcessingFilterTestBase.java
Labels: Enhancement

#1466 docs: remove issue stats, site has been replaced with an unrelated blog
  README.md
  docs/README.md
Labels: enhancement

#1465 docs: automatically add appropriate tag/label to issues created with template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#1464 docs: update reference from Jira to GitHub issues
  .github/SUPPORT.md
Labels: enhancement

#1385 fix(1384): SmartLDAP fixes and improvements
  uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/ChildKeyAsCnModifier.java
  uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/IChildKeyModifier.java
  uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/LdapRecord.java
  uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java
  uPortal-webapp/src/main/resources/org/apereo/portal/groups/smartldap/init.crn
Labels: bug

#1462 feat: extract favicon path as property to be able to customize it wit…
  uPortal-webapp/src/main/java/org/apereo/portal/context/rendering/RenderingPipelineConfiguration.java
  uPortal-webapp/src/main/resources/layout/theme/respondr/respondr.xsl
Labels: enhancement

#1463 feat(skin): apply a default mapping skin
  docs/fr/implementer/frontend/SKIN_UPORTAL.md
  docs/implement/frontend/SKINNING_UPORTAL.md
  uPortal-rendering/src/main/java/org/apereo/portal/rendering/xslt/SkinMappingTransformerConfigurationSource.java
  uPortal-rendering/src/main/java/org/apereo/portal/rendering/xslt/UserAttributeSkinMappingTransformerConfigurationSource.java
  uPortal-rendering/src/main/java/org/apereo/portal/rendering/xslt/UserGroupSkinMappingTransformerConfigurationSource.java
  uPortal-webapp/src/main/java/org/apereo/portal/context/rendering/RenderingPipelineConfiguration.java
Labels: enhancement

#1473 chore: upgrade twitter bootstrap to version 3.4.0
  gradle.properties
Labels: enhancement
