Repository uPortal-Project/uPortal, pull requests merged in 2022-12, with the labels that each got.

#2595 feat(events): add ip address to raw login events
  uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/events/LoginEvent.java
  uPortal-webapp/src/main/resources/properties/portal.properties
Labels: enhancement

#2533 Feat/favorites api
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/dao/portletlist/IPortletList.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/dao/portletlist/IPortletListDao.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/dao/portletlist/IPortletListItem.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/dao/portletlist/jpa/PortletList.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/dao/portletlist/jpa/PortletListDao.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/dao/portletlist/jpa/PortletListItem.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/portletlist/PortletListRESTController.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/utils/ErrorResponse.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/utils/InputValidator.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/services/portletlist/IPortletListService.java
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/services/portletlist/PortletListService.java
  uPortal-webapp/src/main/resources/properties/db/hibernate.cfg.xml
Labels: api/portlet-list

#2597 fix(favorites-api): remove ErrorResponse dup class that exists in uPo…
  uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/utils/ErrorResponse.java
Labels: bug

#2605 fix/java version in CI
  gradle.properties
Labels: bug

#2609 fix: correct some Less entries
  uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/header.less
  uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/regions.less
Labels: bug
